extensions = {
    "text": ".txt",
    "word": ".docx",
    "doc": ".docx",
    "document": ".docx",
    "pdf": ".pdf",
    "ppt": ".pptx",
    "powerpoint": ".pptx",
    "excel": ".xlsx",
    "spreadsheet": ".xlsx",
    "csv": ".csv",
    "python": ".py",
    "java": ".java",
    "c": ".c",
    "cpp": ".cpp",
    "html": ".html",
    "css": ".css",
    "js": ".js",
    "json": ".json",
    "xml": ".xml",
    "yaml": ".yaml",
    "md": ".md",
    "markdown": ".md",
    "log": ".log",
    "ini": ".ini",
    "config": ".cfg",
    "bat": ".bat",
    "sh": ".sh",
    "apk": ".apk",
    "exe": ".exe",
    "zip": ".zip",
    "rar": ".rar",
    "7z": ".7z",
    "tar": ".tar",
    "gz": ".gz",
    "jpg": ".jpg",
    "jpeg": ".jpeg",
    "png": ".png",
    "gif": ".gif",
    "bmp": ".bmp",
    "svg": ".svg",
    "mp3": ".mp3",
    "wav": ".wav",
    "mp4": ".mp4",
    "mkv": ".mkv",
    "avi": ".avi",
    "mov": ".mov",
    "psd": ".psd",
    "ai": ".ai",
    "sketch": ".sketch"
}
file_type_keywords = {
    "text": ["text", "notepad", "txt"],
    "word": ["word", "doc", "document"],
    "pdf": ["pdf"],
    "ppt": ["ppt", "powerpoint", "slides"],
    "excel": ["excel", "spreadsheet", "sheet", "xlsx"],
    "csv": ["csv", "comma separated"],
    "python": ["python", "py"],
    "java": ["java"],
    "c": [" c ", " c file"],
    "cpp": ["cpp", "c++"],
    "html": ["html", "webpage"],
    "css": ["css", "style"],
    "js": ["js", "javascript"],
    "json": ["json"],
    "xml": ["xml"],
    "yaml": ["yaml", "yml"],
    "markdown": ["markdown", "md"],
    "log": ["log", "logging"],
    "ini": ["ini", "initialization"],
    "config": ["config", "cfg", "configuration"],
    "bat": ["bat", "batch"],
    "sh": ["sh", "shell"],
    "apk": ["apk", "android package"],
    "exe": ["exe", "executable"],
    "zip": ["zip"],
    "rar": ["rar"],
    "7z": ["7z"],
    "tar": ["tar"],
    "gz": ["gz", "gzip"],
    "jpg": ["jpg", "jpeg", "image"],
    "png": ["png"],
    "gif": ["gif"],
    "bmp": ["bmp"],
    "svg": ["svg"],
    "mp3": ["mp3", "audio"],
    "wav": ["wav"],
    "mp4": ["mp4", "video"],
    "mkv": ["mkv"],
    "avi": ["avi"],
    "mov": ["mov"],
    "psd": ["psd"],
    "ai": ["ai", "illustrator"],
    "sketch": ["sketch"]
}
